# preload = /home/joskaf/.wallpapers/wallhaven-9dgd2x.jpg
# preload = /home/joskaf/.wallpapers/wallhaven-vqq6jl.png

wallpaper {
    monitor = DP-3
    path = /home/joskaf/.wallpapers/wallhaven-vqq6jl.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/joskaf/.wallpapers/wallhaven-9dgd2x.jpg
    fit_mode = cover
}

splash = false
# ipc = off
