exec eww daemon
exec awww-daemon
exec awww img /home/joskaf/Pictures/wallhaven-d8wxlj.jpg

bind-key layout 0 {
    mod+a focus before
    mod+d focus after

    mod+shift+a move before
    mod+shift+d move after

    mod+ctrl+a swap before
    mod+ctrl+d swap after

    mod+w focus-space before
    mod+s focus-space after

    mod+shift+w move-to-space before
    mod+shift+s move-to-space after

    mod+ctrl+w move-space before
    mod+ctrl+s move-space after

    mod+r add-space after
    mod+shift+r move-to-new-space after

    mod+e add-tile after
    mod+shift+e move-to-new-tile after

    mod+c close-window
    mod+shift+c remove-tile

    mod+x hide-window

    mod+f toggle-floating
    mod+shift+f toggle-focus-floating

    mod+v toggle-fullscreen

    mod+q exec fuzzel
    mod+shift+q exec kitty

    mod+tab switch output
    mod+grave switch hidden

    ctrl+mod+o reload
    ctrl+mod+m exit

    XF86AudioMicMute exec pactl set-source-mute @DEFAULT_SOURCE@ toggle
    XF86AudioMute exec pactl set-sink-mute @DEFAULT_SINK@ toggle
    XF86AudioLowerVolume exec pactl set-sink-volume @DEFAULT_SINK@ -5%
    XF86AudioRaiseVolume exec pactl set-sink-volume @DEFAULT_SINK@ +5%

    shift+XF86AudioMute exec my-playerctl-toggle
    shift+XF86AudioLowerVolume exec playerctl previous
    shift+XF86AudioRaiseVolume exec playerctl next

    XF86AudioPause exec playerctl pause
    XF86AudioPlay exec playerctl play
    XF86AudioNext exec playerctl next
    XF86AudioPrev exec playerctl previous


    XF86MonBrightnessUp exec brightnessctl set 10%+
    XF86MonBrightnessDown exec brightnessctl set 10%-
}

border-width 4
border-color {
    normal b0b0b0
    focused 8080ff
    switch-target ff8000
    switch-preview 808080
}

tile-color {
    normal 20202080
    active-unfocused 80808080
    focused 8080ff80
    focused-single 00000000
}

outer-gap 4
inner-gap 4

smart-borders true
smart-gaps true

switcher-size 800
switcher-opacity 0.8
switcher-delay 100ms
